remote_theme: fongandrew/hydeout
title: Community Sensing
tagline: 'Explorations in Community Sensing'
description: 'A collection of resources for building social or community sensing systems.'
url: https://dr-jgsmith.github.io

author:
  name:'Justin G. Smith'

paginate: 5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
