remote_theme: fongandrew/hydeout
title: Social Sensing
description: 'A collection of resources for building social sensing systems.'
url: https://dr-jgsmith.github.io

author:
  name: 'Justin G. Smith'

paginate: 5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
